# Generated by Django 5.1.7 on 2025-04-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('year_built', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings/')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='districts/')),
            ],
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_type', models.CharField(choices=[('Banc1', 'Банке не обманывает'), ('Banc2', 'Может гдето и обмани'), ('Banc3', 'Сто процентов обманываем'), ('Banc4', 'Сто процентов не обманываем')], max_length=50, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='Подписчик', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('square_footage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments/images/')),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('finishing', models.CharField(choices=[('', 'Любая отделка'), ('черновая', 'Черновая'), ('чистовая', 'Чистовая'), ('евро', 'Евроремонт'), ('дизайнерский', 'Дизайнерский')], default='', max_length=20, verbose_name='Тип отделки')),
                ('allow_multiple_purchases', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplomapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diplomapp.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplomapp.district'),
        ),
        migrations.CreateModel(
            name='InfrastructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('clinic', 'Поликлиника'), ('park', 'Парк'), ('parking', 'Парковка'), ('school', 'Школа'), ('kindergarten', 'Детский сад'), ('cafe', 'Кафе'), ('shop', 'Магазин'), ('pharmacy', 'Аптека')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='infrastructure/')),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='diplomapp.building')),
            ],
        ),
    ]
