# Generated by Django 5.1.7 on 2025-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(default='Default Building', max_length=100),
            preserve_default=False,
        ),
    ]
