# Generated by Django 5.1.7 on 2025-03-19 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0005_chat_alter_interestrate_calculator_type_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 19, 19, 54, 19, 312779, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
