# Generated by Django 5.1.7 on 2025-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0006_apartment_created_at_apartment_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='finishing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
