# Generated by Django 5.1.7 on 2025-03-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0008_apartment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatResidentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplomapp.chat')),
            ],
        ),
    ]
