# Generated by Django 5.1.7 on 2025-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0009_chatresidentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='allow_multiple_purchases',
            field=models.BooleanField(default=False),
        ),
    ]
