# Generated by Django 5.1.7 on 2025-03-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0010_apartment_allow_multiple_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrate',
            name='calculator_type',
            field=models.CharField(choices=[('cto % obman', 'Сто процентов обманываем'), ('moxet obmanl', 'Может гдето и обмани'), ('banc ne obman', 'Банке не обманываетм')], max_length=50, unique=True),
        ),
    ]
