# Generated by Django 5.1.7 on 2025-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0011_alter_interestrate_calculator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrate',
            name='calculator_type',
            field=models.CharField(choices=[('standard', 'Банке не обманывает'), ('preferential', 'Может гдето и обмани'), ('business', 'Сто процентов обманываем')], max_length=50, unique=True),
        ),
    ]
