# Generated by Django 5.1.7 on 2025-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0012_alter_interestrate_calculator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/'),
        ),
    ]
