# Generated by Django 5.1.7 on 2025-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0013_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='districts/'),
        ),
    ]
