# Generated by Django 5.1.7 on 2025-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0014_district_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='ChatResidentEmail',
        ),
    ]
