# Generated by Django 5.1.7 on 2025-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0015_chatmember_email_delete_chatresidentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to='media/apartments/images/'),
        ),
    ]
