# Generated by Django 5.1.7 on 2025-04-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0016_alter_apartmentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/apartments/images/'),
        ),
    ]
