# Generated by Django 5.1.7 on 2025-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0017_alter_apartment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrate',
            name='calculator_type',
            field=models.CharField(choices=[('Banc1', 'Банке не обманывает'), ('Banc2', 'Может гдето и обмани'), ('Banc3', 'Сто процентов обманываем'), ('Banc4', 'Сто процентов не обманываем')], max_length=50, unique=True),
        ),
    ]
