# Generated by Django 5.1.7 on 2025-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0018_alter_interestrate_calculator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='finishing',
            field=models.CharField(choices=[('', 'Любая отделка'), ('черновая', 'Черновая'), ('чистовая', 'Чистовая'), ('евро', 'Евроремонт'), ('дизайнерский', 'Дизайнерский')], default='', max_length=20, verbose_name='Тип отделки'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/images/'),
        ),
    ]
