# Generated by Django 5.1.7 on 2025-04-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0019_alter_apartment_finishing_alter_apartment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Название иконки из Font Awesome', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('clinic', 'Поликлиника'), ('park', 'Парк'), ('parking', 'Парковка'), ('school', 'Школа'), ('kindergarten', 'Детский сад'), ('cafe', 'Кафе'), ('shop', 'Магазин')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('distance', models.CharField(help_text='Например: 500 м или 10 мин пешком', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='infrastructure/')),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='diplomapp.building')),
            ],
        ),
    ]
