# Generated by Django 5.1.7 on 2025-04-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0020_infrastructuretype_infrastructureitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='distance',
        ),
        migrations.AlterField(
            model_name='infrastructureitem',
            name='type',
            field=models.CharField(choices=[('clinic', 'Поликлиника'), ('park', 'Парк'), ('parking', 'Парковка'), ('school', 'Школа'), ('kindergarten', 'Детский сад'), ('cafe', 'Кафе'), ('shop', 'Магазин'), ('pharmacy', 'Аптека')], max_length=20),
        ),
    ]
