# Generated by Django 5.1.7 on 2025-04-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0021_remove_infrastructureitem_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='website',
        ),
    ]
