# Generated by Django 5.1.7 on 2025-04-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0023_infrastructurecategory_alter_apartmentimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructureitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='InfrastructureCategory',
        ),
    ]
