# Generated by Django 5.1.7 on 2025-04-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0025_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmember',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMember',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
