# Generated by Django 5.1.7 on 2025-04-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomapp', '0026_remove_chatmember_chat_remove_chatmessage_chat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfrastructureType',
        ),
    ]
